name: OpenInv CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - resource-pack/**
  # Enable running CI via other Actions, i.e. for drafting releases and handling PRs.
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      # Upload artifacts
      - name: Upload Distributable Jar
        id: upload-final
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./plugin/build/libs/*-all.jar
      - name: Upload API Jar
        id: upload-api
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./api/build/libs/openinvapi*.jar
