name: OpenInv CI

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'
    paths-ignore:
      - resource-pack/openinv-legibility-pack/**
  # Enable running CI via other Actions, i.e. for drafting releases and handling PRs.
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # TODO convert to a Gradle plugin later for portability
      - name: Install Spigot dependency
        run: ./scripts/install_spigot.sh 1.21.4

      - uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      # Upload artifacts
      - name: Upload Distributable Jar
        id: upload-final
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/*
