name: OpenInv CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Install Spigot dependencies if necessary.
      - name: Install Spigot Dependencies
        run: . scripts/install_spigot_dependencies.sh

      - name: Build With Maven
        run: mvn -e clean package -am -P all

      # Upload artifacts
      - name: Upload Distributable Jar
        id: upload-final
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./target/OpenInv.jar
      - name: Upload API Jar
        id: upload-api
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./api/target/openinvapi*.jar
