name: Draft Github Release

on:
  push:
    tags:
      - '**'

jobs:
  run-ci:
    uses: Jikoo/OpenInv/.github/workflows/ci.yml@master
  draft-release:
    needs: [ run-ci ]
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: OpenInv ${{ env.VERSIONED_NAME }}
          # May actually want to manually specify Paper versions all the time; they won't all
          # need to be specified in code thanks to Mojang-mapped server internals.
          # A bit annoying, but not terribly so.
          # Instead, fetch min and max (which will also be Spigot version) and manually list intermediate versions?
          body: |-
            ## Supported server versions
            **Paper:** TODO COMMA-SEPARATED VERSIONS
            **Spigot:** TODO VERSION
            
            TODO HELLO HUMAN, PRESS THE GENERATE CHANGELOG BUTTON PLEASE.
          draft: true
          prerelease: false
          files: ./dist/**
